py.install_sources(
  [
    'main.py',
    'window.py',
    'cd_manager.py',
    'cd_reader.py',
    'cd_ripper.py',
    'i18n.py',
    'settings.py',
    '__init__.py',
  ],
  subdir: 'src'
)

py.install_sources(
  [
    'ui/__init__.py',
    'ui/track_list.py',
    'ui/status_page.py',
    'ui/preferences.py',
    'ui/about.py',
  ],
  subdir: 'src/ui'
)
